// This file drives the real verify-release.sh against a synthetic release built in a
// temporary directory: two assets, a manifest listing both, and a signature over it. Every
// key here is generated by the test, so nothing depends on the key the repository ships.
package deploy_test

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const verifier = "./verify-release.sh"

// release is a synthetic release on disk, as an operator would have downloaded it.
type release struct {
	dir   string
	asset string // the artifact under test, an absolute path
	other string // a second asset, so a rename has somewhere to go
	sums  string
	sig   string
	pub   string
	priv  string
}

func openssl(t *testing.T, args ...string) {
	t.Helper()
	if out, err := exec.Command("openssl", args...).CombinedOutput(); err != nil {
		t.Fatalf("openssl %s: %v\n%s", strings.Join(args, " "), err, out)
	}
}

// keyPair writes an ECDSA P-256 pair into dir under the given base name.
func keyPair(t *testing.T, dir, name string) (priv, pub string) {
	t.Helper()
	priv = filepath.Join(dir, name+".priv")
	pub = filepath.Join(dir, name+".pub")
	openssl(t, "ecparam", "-name", "prime256v1", "-genkey", "-noout", "-out", priv)
	openssl(t, "ec", "-in", priv, "-pubout", "-out", pub)
	return priv, pub
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func digest(t *testing.T, path string) string {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}

// sign replaces the manifest's signature, so a test that rewrote the manifest can re-sign it.
func (r release) sign(t *testing.T, priv string) {
	t.Helper()
	openssl(t, "dgst", "-sha256", "-sign", priv, "-out", r.sig, r.sums)
}

// writeManifest lists every asset in the directory, in sha256sum's own format.
func (r release) writeManifest(t *testing.T, assets ...string) {
	t.Helper()
	lines := ""
	for _, asset := range assets {
		lines += fmt.Sprintf("%s  %s\n", digest(t, asset), filepath.Base(asset))
	}
	write(t, r.sums, lines)
}

func newRelease(t *testing.T) release {
	t.Helper()
	dir := t.TempDir()
	r := release{
		dir:   dir,
		asset: filepath.Join(dir, "monitor-agent-1.2.3-linux-amd64"),
		other: filepath.Join(dir, "monitor-hub-1.2.3-linux-amd64"),
		sums:  filepath.Join(dir, "SHA256SUMS"),
	}
	r.sig = r.sums + ".sig"
	r.priv, r.pub = keyPair(t, dir, "release-signing-key")
	write(t, r.asset, "the agent binary\n")
	write(t, r.other, "the hub binary\n")
	r.writeManifest(t, r.asset, r.other)
	r.sign(t, r.priv)
	return r
}

// verifierPath is the script under test, as an absolute path: a run is started from the
// directory that holds the key it is meant to find.
func verifierPath(t *testing.T) string {
	t.Helper()
	path, err := filepath.Abs(verifier)
	if err != nil {
		t.Fatal(err)
	}
	return path
}

// verify runs the real script with nothing inherited but PATH, so no OPENSSL_CONF or locale
// of the machine running the tests reaches it. An empty pathDir keeps the caller's own PATH.
func verify(t *testing.T, script, pathDir string, args ...string) (stdout, stderr string, err error) {
	t.Helper()
	command := exec.Command("sh", append([]string{script}, args...)...)
	if pathDir == "" {
		pathDir = os.Getenv("PATH")
	}
	command.Env = []string{"PATH=" + pathDir}
	var out, errs strings.Builder
	command.Stdout = &out
	command.Stderr = &errs
	err = command.Run()
	return out.String(), errs.String(), err
}

// verifyAsset is the common case: the repository's script, the release's own key.
func (r release) verifyAsset(t *testing.T, args ...string) (stdout, stderr string, err error) {
	t.Helper()
	return verify(t, verifierPath(t), "", append([]string{"--key", r.pub}, args...)...)
}

// spec: release.md#verifying-an-artifact — an asset, manifest and signature as published
// verify, whether or not the manifest is named explicitly.
func TestAnAssetFromTheReleaseVerifies(t *testing.T) {
	r := newRelease(t)

	stdout, stderr, err := r.verifyAsset(t, r.asset)
	if err != nil {
		t.Fatalf("verifying a published asset failed: %v\n%s%s", err, stdout, stderr)
	}

	stdout, stderr, err = r.verifyAsset(t, "--sums", r.sums, r.asset)
	if err != nil {
		t.Fatalf("naming the manifest explicitly failed: %v\n%s%s", err, stdout, stderr)
	}
}

// spec: release.md#verifying-an-artifact — with no --key the script reads the key beside
// itself, which in a release-era checkout is the one the repository ships.
func TestARunWithNoOptionsUsesTheKeyBesideTheScript(t *testing.T) {
	r := newRelease(t)
	// A directory of its own, so a script that looked for the key beside the artifact
	// instead of beside itself would fail this test rather than pass it by coincidence.
	scriptDir := t.TempDir()
	script := filepath.Join(scriptDir, "verify-release.sh")
	source, err := os.ReadFile(verifier)
	if err != nil {
		t.Fatal(err)
	}
	write(t, script, string(source))
	key, keyErr := os.ReadFile(r.pub)
	if keyErr != nil {
		t.Fatal(keyErr)
	}
	write(t, filepath.Join(scriptDir, "release-signing-key.pub"), string(key))
	// A decoy under the same name beside the artifact: a script looking there would now
	// verify with the wrong key and fail, instead of passing by coincidence.
	_, decoy := keyPair(t, t.TempDir(), "decoy")
	decoyKey, decoyErr := os.ReadFile(decoy)
	if decoyErr != nil {
		t.Fatal(decoyErr)
	}
	write(t, r.pub, string(decoyKey))

	stdout, stderr, err := verify(t, script, "", r.asset)
	if err != nil {
		t.Fatalf("a run with no options failed: %v\n%s%s", err, stdout, stderr)
	}
}

// spec: release.md#verifying-an-artifact — every way an artifact can fail to be the one the
// release named, and every way the run can be asked the question wrongly.
func TestAVerificationThatMustFail(t *testing.T) {
	tests := []struct {
		name    string
		prepare func(t *testing.T, r *release) []string // returns the arguments to run with
		names   string                                  // what the message must name
		usage   bool                                    // and whether it prints the usage
	}{
		{
			name: "an asset changed by one byte",
			prepare: func(t *testing.T, r *release) []string {
				write(t, r.asset, "the agent binary, tampered with\n")
				return []string{r.asset}
			},
			names: "is not the file",
		},
		{
			name: "an asset renamed to another asset's name",
			prepare: func(t *testing.T, r *release) []string {
				renamed := filepath.Join(r.dir, "monitor-hub-1.2.3-linux-amd64")
				if err := os.Rename(r.asset, renamed); err != nil {
					t.Fatal(err)
				}
				return []string{renamed}
			},
			names: "is not the file",
		},
		{
			name: "an artifact the manifest does not list",
			prepare: func(t *testing.T, r *release) []string {
				stranger := filepath.Join(r.dir, "monitor-agent-9.9.9-linux-amd64")
				write(t, stranger, "a binary from nowhere\n")
				return []string{stranger}
			},
			names: "does not list monitor-agent-9.9.9-linux-amd64",
		},
		{
			name: "a manifest changed after signing",
			prepare: func(t *testing.T, r *release) []string {
				write(t, r.asset, "a replacement binary\n")
				r.writeManifest(t, r.asset, r.other)
				return []string{r.asset}
			},
			names: "does not verify",
		},
		{
			name: "a manifest signed by another key",
			prepare: func(t *testing.T, r *release) []string {
				other, _ := keyPair(t, r.dir, "someone-else")
				r.sign(t, other)
				return []string{r.asset}
			},
			names: "does not verify",
		},
		{
			name: "no manifest beside the artifact",
			prepare: func(t *testing.T, r *release) []string {
				if err := os.Remove(r.sums); err != nil {
					t.Fatal(err)
				}
				return []string{r.asset}
			},
			names: "no manifest",
		},
		{
			name: "no signature beside the manifest",
			prepare: func(t *testing.T, r *release) []string {
				if err := os.Remove(r.sig); err != nil {
					t.Fatal(err)
				}
				return []string{r.asset}
			},
			names: "no signature",
		},
		{
			name: "a signature file that is empty",
			prepare: func(t *testing.T, r *release) []string {
				write(t, r.sig, "")
				return []string{r.asset}
			},
			names: "does not verify",
		},
		{
			name: "a signature file that is not a signature",
			prepare: func(t *testing.T, r *release) []string {
				write(t, r.sig, "not a signature at all\n")
				return []string{r.asset}
			},
			names: "does not verify",
		},
		{
			name: "no artifact named",
			prepare: func(_ *testing.T, _ *release) []string {
				return nil
			},
			names: "no artifact named",
			usage: true,
		},
		{
			name: "more than one artifact named",
			prepare: func(_ *testing.T, r *release) []string {
				return []string{r.asset, r.other}
			},
			names: "one artifact at a time",
			usage: true,
		},
		{
			name: "a directory named",
			prepare: func(_ *testing.T, r *release) []string {
				return []string{r.dir}
			},
			names: "is not a file",
			usage: true,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			r := newRelease(t)
			args := test.prepare(t, &r)

			stdout, stderr, err := r.verifyAsset(t, args...)
			if err == nil {
				t.Fatalf("the run succeeded; it had to fail\n%s%s", stdout, stderr)
			}
			if test.names != "" && !strings.Contains(stderr, test.names) {
				t.Errorf("the message does not name %q:\n%s", test.names, stderr)
			}
			if test.usage != strings.Contains(stderr, "usage:") {
				t.Errorf("usage printed = %v, want %v:\n%s", !test.usage, test.usage, stderr)
			}
		})
	}
}

// spec: release.md#verifying-an-artifact — a key that cannot be used is not a bad signature,
// and the run says which of the two it met.
func TestAKeyThatCannotBeUsedIsNamed(t *testing.T) {
	tests := []struct {
		name string
		says string // the half of the message that says which of the two it met
		key  func(t *testing.T, r release) string
	}{
		{
			name: "a path that does not exist",
			says: "no public key at",
			key: func(_ *testing.T, r release) string {
				return filepath.Join(r.dir, "no-such-key.pub")
			},
		},
		{
			name: "a file that is not a key at all",
			says: "is not a public key",
			key: func(t *testing.T, r release) string {
				path := filepath.Join(r.dir, "notes.pub")
				write(t, path, "this is prose, not a key\n")
				return path
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			r := newRelease(t)
			key := test.key(t, r)

			stdout, stderr, runErr := verify(t, verifierPath(t), "", "--key", key, r.asset)
			if runErr == nil {
				t.Fatalf("the run succeeded; it had to fail\n%s%s", stdout, stderr)
			}
			if !strings.Contains(stderr, key) {
				t.Errorf("the message does not name the key %q:\n%s", key, stderr)
			}
			if !strings.Contains(stderr, test.says) {
				t.Errorf("the message does not say %q:\n%s", test.says, stderr)
			}
			// The point of naming the key is that this is not read as tampering.
			if strings.Contains(stderr, "does not verify") {
				t.Errorf("an unusable key is reported as a bad signature:\n%s", stderr)
			}
		})
	}
}

// spec: release.md#verifying-an-artifact — a failure names the key and the manifest it used,
// so a rotation that left an old key behind is not read as tampering.
func TestAFailureNamesTheKeyAndTheManifestItUsed(t *testing.T) {
	r := newRelease(t)
	write(t, r.asset, "the agent binary, tampered with\n")

	stdout, stderr, err := r.verifyAsset(t, r.asset)
	if err == nil {
		t.Fatalf("the run succeeded; it had to fail\n%s%s", stdout, stderr)
	}
	for _, want := range []string{r.pub, r.sums} {
		if !strings.Contains(stderr, want) {
			t.Errorf("the message does not name %q:\n%s", want, stderr)
		}
	}
}

// spec: release.md#verifying-an-artifact — openssl is the one tool the verifier needs, and a
// machine without it is told so rather than told the artifact is bad.
func TestARunWithoutOpensslNamesIt(t *testing.T) {
	r := newRelease(t)

	stdout, stderr, runErr := verify(t, verifierPath(t), t.TempDir(), "--key", r.pub, r.asset)
	if runErr == nil {
		t.Fatalf("the run succeeded; it had to fail\n%s%s", stdout, stderr)
	}
	if !strings.Contains(stderr, "openssl") {
		t.Errorf("the message does not name openssl:\n%s", stderr)
	}
}

// spec: release.md#the-key — the public half is committed, and a run with no --key is only
// as good as that file: without it every release run and every operator command fails.
func TestTheShippedKeyIsAPublicKeyOpensslCanRead(t *testing.T) {
	const shipped = "release-signing-key.pub"
	if _, err := os.Stat(shipped); err != nil {
		t.Fatalf("the repository ships no %s: %v", shipped, err)
	}
	if out, err := exec.Command("openssl", "pkey", "-pubin", "-in", shipped, "-noout").CombinedOutput(); err != nil {
		t.Errorf("%s is not a public key openssl can read: %v\n%s", shipped, err, out)
	}
}

// spec: release.md#verifying-an-artifact — -h is a request: the usage goes to stdout and the
// run succeeds. The PATH holds nothing, so this also pins openssl as the only command
// outside the shell that the script needs.
func TestHelpPrintsTheUsageOnStdoutAndSucceeds(t *testing.T) {
	stdout, stderr, err := verify(t, verifierPath(t), t.TempDir(), "-h")
	if err != nil {
		t.Fatalf("-h failed: %v\n%s%s", err, stdout, stderr)
	}
	if !strings.Contains(stdout, "usage:") {
		t.Errorf("the usage is not on stdout:\n%s", stdout)
	}
	if stderr != "" {
		t.Errorf("-h wrote to stderr:\n%s", stderr)
	}
}
